name: Example

on:
  pull_request:
    branches: [ master ]

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
        
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Php example
      run: php index.php ${{ github.actor }}
      
    - name: Node example
      run: node index.js ${{ github.actor }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        uses: docker/build-push-action@v1
        with:
         repository: ${{ github.repository }}
         tag_with_ref: true
         tags: latest
         push: false

      - name: Test build
        run: docker run --rm --name test-image ${{ github.repository }}:latest ${{ github.actor }}
